version: "2.4"
services:
  test1:
    image: netsim:latest
    entrypoint: ""
    command: bash -c 'ip route add 172.29.1.0/24 via 172.28.1.2 dev eth0 && ip route show && ping 172.29.1.3'
    cap_add: [NET_ADMIN]
    networks:
      test_net1:
        ipv4_address: 172.28.1.3
  test2:
    image: netsim:latest
    entrypoint: ""
    command: bash -c 'ip route add 172.28.1.0/24 via 172.29.1.2 dev eth0 && ip route show && ping 172.28.1.3'
    cap_add: [NET_ADMIN]
    networks:
      test_net2:
        ipv4_address: 172.29.1.3
  test_bridge:
    image: netsim:latest
    command: bash -c 'ping localhost > /dev/null'
    networks:
      test_net1:
        ipv4_address: 172.28.1.2
      test_net2:
        ipv4_address: 172.29.1.2

networks:
  test_net1:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
  test_net2:
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/24
